version: '3.8'

services:
  scraper:
    build: .
    depends_on:
      selenium:
        condition: service_healthy
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
#      - SELENIUM_URL=http://127.0.0.1:4444
    volumes:
      - ./results:/app/results


  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: '2gb'
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
#      test: ["CMD", "curl", "-f", "http://localhost:4444"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s